---
title: "Wczytywanie obrazów satelitarnych do R"
author: "Mateusz Zółtak"
date: "30 lipca 2016"
output: html_document
---

# Przygotowanie

Załadujmy potrzebne pakiety.

```{r, message=FALSE, warning=FALSE}
library(WicPomiarSatelitarny)
```

# Puławy

## Pobranie danych

Pobierzmy zdjęcia od 29 czerwca do dziś, ale tylko takie, dla których zachmurzenie nie przekraczało 60%.  
(pozycja Puław to z grubsza 21.95 E, 51.41 N)

```{r}
zdjPulawy = pobierzZdjecia(21.95, 51.41, "2016-06-29", "2016-08-19", 60, "dane/Pulawy", "auto")
```

## Generowanie obrazów kolorowych

```{r}
# stwórz listę obiektów R na podstawie zdjęć zapisanych na dysku
zdjecia = wczytajZdjecia("dane", "2016-06-29")

# skomponuj obraz kolorowy z trzech wskazanych pasm
eksportujKolor(zdjecia[["B04"]], zdjecia[["B03"]], zdjecia[["B02"]], 'dane/Pulawy/rgb.tif', 0, 5000)

# pokoloruj klasyfikację scen w zadany sposób
eksportujMono(zdjecia[["SCL"]], "dane/Pulawy/scl.tif", 0, 11, c('red', 'red', 'white', 'white', 'green', 'brown', 'blue', 'white', 'white', 'white', 'white', 'white'))

# pokoloruj pasmo wegetacji na zielono
eksportujMono(zdjecia[["B8A"]], "dane/Pulawy/B8A_kolor.tif", 0, 3000, c('grey', ''))
```

## NDVI

```{r}
zdjecia[["NDVI"]] = (zdjecia[["B8A"]] - zdjecia[["B04"]]) / (zdjecia[["B8A"]] + zdjecia[["B04"]])
```

```{r}
tmp = cut(zdjecia[["B04"]], breaks = c(100, 1000, 2000, 3000, 4000))
plot(tmp)
eksportujMono(tmp, "dane/tmp.tif", paleta = c('grey', 'green'))
eksportujMono(zdjecia[["B04"]], "dane/tmp.tif", 0, 4000, paleta = c('white', 'green'))


levelplot(zdjecia[['SCL']])
tmp = ratify(bands[['SCL']])
levels(tmp) = data.frame()

ggplot(values, aes(x = NDVI, y = LAI)) + geom_bin2d(binwidth = c(0.05, 100))
ggplot(values[values$SCL < 7 & values$SCL > 3, ], aes(x = NDVI, y = LAI)) + geom_bin2d(binwidth = c(0.05, 100))

out = raster('dane/B02.tiff')
out = setValues(out, ifelse(values$NDVI < 0.2 & values$NDVI > 0 & values$LAI > 1300 & values$LAI < 2000, 1, NA))


model = lm(LAI ~ B02 + B03 + B04 + B05 + B06 + B07 + B8A + B09 + B11 + B12, data = values[values$SCL < 7 & values$SCL > 3, ])
```

# Pożar w Fort McMurray (Kanada)

```{r}
mcmurray = pobierzZdjecia(-111.37, 56.70, "2016-04-15", "2016-04-30", 50, "dane/McMurray")
for(data in c("2016-04-29", "2016-05-02", "2016-05-05", "2016-05-12", "2016-05-15", "2016-05-25")){
  zdjecia = wczytajZdjecia("dane/McMurray", data, skorAtm = FALSE)
  #eksportujKolor(zdjecia[["B04"]], zdjecia[["B03"]], zdjecia[["B02"]], paste0('dane/McMurray/rgb_', data, '.tif'), 0, 2000)
  eksportujMono(zdjecia[["B08"]], paste0('dane/McMurray/nir_', data, '.tif'), 0, 3000, paleta = c('white', 'red'))
}

```